interim check
KristinaYandex/react-stellar-burger pull request #1
Opened 2023-05-01 11:03 UTC by KristinaYandex

Отправка первой части проекта на промежуточную проверку.

2023-05-02 13:30 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали хорошую работу на старте вашего проекта, верстка аккуратная, в коде не содержится лишних элементов, хорошо прописаны `PropTypes`, добавлен скролл по клику на таб к нужной категории, **так держать** 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Булки в конструкторе следует расположить сверху и снизу списка ингредиентов (см. https://disk.yandex.ru/i/tVHNJMkic0cO-A);
- Некорректно отображается счетчик ингредиента, убежал в правый верхний угол (см. https://disk.yandex.ru/i/YiwwXwTXChiUiA). Возможно, значение `position: relative` не задано у родительского элемента;
- Названия файлов следует привести к виду `kebab-case`;
- Названия переменных и функций следует приводить к виду `camelCase`;
- Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

Также, в рамках ревью были предложены **улучшения** вашего кода, которые могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-05-02 13:30 UTC, randomroot commented on src/components/app/app.jsx
>        	margin: "auto",
🟡 **Можно улучшить:**

Данный элемент уже не требуется :)

2023-05-02 13:30 UTC, randomroot commented on src/components/burgeringredients/burgeringredients.js
> +    const [current, setCurrent] = React.useState("buns");
🟡 **Можно улучшить:**

Варианты значения стейта имеет смысл вынести в отдельные константы или объединить под одной константой, чтобы их было удобно переиспользовать в рамках файла и при необходимости изменить содержимое только в одном месте, вместо множества, например:
```typescript
const Tabs = {
  BUN: 'bun',
  SAUCE: 'sauce'
  ...
}

... = useState(Tabs.BUN)
```

2023-05-02 13:30 UTC, randomroot commented on src/components/burgeringredients/burgeringredients.js
> +        <div className={burgerIngredients.menu} style={{ display: 'flex' }}>
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2023-05-02 13:30 UTC, randomroot commented on src/components/burgeringredients/burgeringredients.js
> +          <h2 className="text text_type_main-medium" id="buns" ref={ingredientsforburgerRef}>Булки</h2>
🟡 **Можно улучшить:**

Обратите внимание, что категории ингредиентов одинаковы по коду, поэтому имеет смысл вынести их в отдельный файл

🔴 **Нужно исправить:**

Названия переменных и функций следует приводить к виду `camelCase`

2023-05-02 13:30 UTC, randomroot commented on src/components/burgeringredients/burgeringredients.js
> +    const scrollRef = useRef(null);
🟢 **Отлично:**

Классно, что сделали скролл к разделу!

2023-05-02 13:30 UTC, randomroot commented on src/utils/prop-types.js
> +  _id: PropTypes.string,
🟡 **Можно улучшить:**

Обратите внимание, что ключи также могут быть обязательными `isRequired`

2023-05-02 17:07 UTC, KristinaYandex commented on src/utils/prop-types.js
> +  _id: PropTypes.string,
Добрый день. Исправила все замечания, благодарю за предложения по улучшению моей работы.

2023-05-03 05:29 UTC, randomroot approved these changes
🟡**Предварительный этап принят (с комментариями)**

**Добрый день!**

Вы успешно скорректировали указанные в работе недостатки, однако на следующем этапе вам необходимо обратить внимание на комментарии, оставленные в рамках текущего ревью, и **исправить** подсвеченные моменты:

- Типы пропсов следует описывать через ключевое слово `propTypes`;
- При использовании функции `map` следует указывать пропс `key` уникальный и неизменяющийся со временем для каждого элемента;

Тем не менее, вы **можете приступать** к выполнению **второй** части вашего задания. Данный `PR` можно сливать в ветку `main` или продолжать работу в ней, как вам будет удобнее 🐈 

**Хорошего вам дня!** ☀️

2023-05-03 05:29 UTC, randomroot commented on src/components/ingredient-burger/ingredient-burger.js
> +IngredientBurger.PropType = {
🔴 **Нужно исправить:**

Типы `PropTypes` следует прописывать через `IngredientBurger.propTypes` (обратите внимание на слово после точки). **Здесь и в других местах в рамках проекта**

2023-05-03 05:29 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.js
> +    const Tabs = {
🟡 **Можно улучшить:**

Такие константы имеет смысл выносить за пределы компонента, чтобы они не пересоздавались на каждом его рендере

2023-05-03 05:29 UTC, randomroot commented on src/components/burger-components/burger-components.js
> +          <IngredientBurger ingredient={ingredient} />
🔴 **Нужно исправить:**

При использовании функции `map` для генерации набора JSX элементов, следует каждому из них передавать значение ключа (пропс `key`). Ключ - это **уникальное** и не **изменяющееся со временем** значение по которому React поймет, нужно ли этот элемент перерисовывать заново. Их отсутствие может привести к лишним ре-рендерам и потери производительности всего приложения в целом. 

Попробуйте подобрать или сгенерировать уникальный для каждого случая ключ, например здесь может подойти вариант с element._id - идентификаторы это то что нужно :)

2023-05-07 11:35 UTC, merged